#Builder Stage
#베이스 이미지 명시
FROM node:18-alpine as frontend-builder

#이미지안에서 어플리케이션 소스코드를 가지고 있을 디렉토리를 생성
WORKDIR /app

#Copy를 통해 컨테이너 안으로 이동시켜준다
#Copy { 로컬에 있는 파일을 복사할 경로 } { 도커 컨테이너 내에서 파일을 복사할경로 }
COPY package.json /app/package.json

RUN npm install

COPY . /app
#next의경우 build 할떄 CMD대신 RUN이여야 빌드가된다
RUN npm run build

#EXPOSE 3000

#CMD ["npm", "run" ,"start"]

 #RUN Stage
 FROM nginx:latest

 RUN rm -rf /etc/nginx/conf.d
 COPY staticConf /etc/nginx

 #포트
 EXPOSE 3000

 #next.js 로 build시 next 생성
 COPY --from=frontend-builder /app/out /usr/share/nginx/html

 # # 컨테이너 내부 끼리 사용할 port를 허용해준다
 CMD ["nginx", "-g", "daemon off;"]
