#도커 버전
version: "3"
services:
  flly_fe:
    image: wjdgusaho/flowerly_fe
    build:
      dockerfile: DockerFile
      context: ./Frontend
    container_name: flly_fe
    volumes:
      - ./Frontend:/app
      - /app/node_modules
      - /app/.next
    stdin_open: true
    restart: always
    expose:
      - "3000"
    ports:
      - "3000:3000"

  flly_be:
    image: wjdgusaho/flowerly_be
    build:
      dockerfile: DockerFile
      context: ./Backend
    container_name: flly_be
    volumes:
      - ./Backend:/app
    restart: always
    expose:
      - "9999"
    ports:
      - "9999:9999"
