#도커 버전
version: "3"
services:
  flly_fe:
    image: wjdgusaho/flowerly_fe
    build:
      dockerfile: DockerFile
      context: ./Frontend
    container_name: flly_fe
    # volumes:
    #  - ./Frontend:/app
    #  - /app/node_modules
    #  - /app/.next
    stdin_open: true
    # restart: always
    expose:
      - "3000"

  flly_be:
    image: wjdgusaho/flowerly_be
    build:
      dockerfile: DockerFile
      context: ./Backend
    container_name: flly_be
    volumes:
      - ./Backend:/app
    restart: always
    expose:
      - "6090"

  mariadb:
    container_name: mariadb
    image: mariadb:11.0.3
    volumes:
      - /home/ubuntu/mysqlConfig:/var/lib/mysql
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      - TZ=Asia/Seoul
      - MYSQL_ROOT_PASSWORD=flowerlybe-209
